### ISSUE TITLE
needs methods textFieldDidBeginEditing and textFieldDidEndEditing

### ISSUE THREAD

**Issue by sundialsoft** [B-Sides/ELCTextFieldCell#4]
to make it work like regular text fields, something like:-
- (void)textFieldDidBeginEditing:(UITextField *)textField {
  
  if([delegate respondsToSelector:@selector(textFieldDidBeginEditing:)]) {
  
  ```
  [delegate performSelector:@selector(textFieldDidBeginEditing:) withObject:indexPath];
  ```
  
  }
  
  return;
  }
- (void)textFieldDidEndEditing:(UITextField *)textField {
  
  if([delegate respondsToSelector:@selector(textFieldDidEndEditing:)]) {
  
  ```
  [delegate performSelector:@selector(textFieldDidEndEditing:) withObject:indexPath];
  ```
  
  }
  
  return;
  }

ps: This is a very useful tool for working with simple forms & it's much easier to implement than some of the bigger options.

**Comment by jvanmetre** [comment]
Thanks for the response, you will find these new optional methods in the latest code base.
