### ISSUE TITLE
Xcode warning: 'UITextAlignmentRight' is deprecated

### ISSUE THREAD

**Issue by jhogervorst** [B-Sides/ELCTextFieldCell#5]
> ELCTextFieldCell/Classes/ELCTextFieldCell.m:43:32:
> 'UITextAlignmentRight' is deprecated:
> first deprecated in iOS 6.0

**Comment by bourou01** [comment]
+1

**Comment by jvanmetre** [comment]
I just pushed version 0.2.0, which drops UITextAlignment, updates to arc, and changes minimum iOS to 6.0.
