### ISSUE TITLE
Looks bad in iOS7

### ISSUE THREAD

**Issue by fulldecent** [B-Sides/ELCTextFieldCell#6]
In the demo, if I add

```
    if (indexPath.row == 3) {
        UITableViewCell *cell2 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue2 reuseIdentifier:@"ttt"];
        cell2.textLabel.text = @"hello";
        cell2.detailTextLabel.text= @"world";
        return cell2;
    }
```

It looks like this:

![ios simulator screen shot nov 7 2013 6 34 46 pm](https://f.cloud.github.com/assets/382183/1497022/314c3192-4805-11e3-81b8-eaf0705149df.png)

**Comment by jvanmetre** [comment]
The cell wasn't ever intentionally designed to exactly mimic the UITableViewCellStyleValue2, however it was designed to be easily customized for the font, and color. If you are using this on iOS 7, all you would need to do, is add some custom code after the cell's initial init.

```
    if (cell == nil) {
        cell = [[ELCTextFieldCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier];
        if ([cell respondsToSelector:@selector(tintColor)]) {
            cell.leftLabel.textColor = cell.tintColor;
            cell.leftLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
            cell.leftLabel.textAlignment = NSTextAlignmentRight;
            cell.rightTextField.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
        }
    }
```

Much like a lot of apps customize the textLabel and detailTextLabel fonts / colors.
